steps:
  # 步骤1: 构建 Go 应用
  - name: 'gcr.io/cloud-builders/go'
    args: ['build', '-o', 'main', '.']
    env:
      - 'CGO_ENABLED=0'
      - 'GOOS=linux'
      - 'GOARCH=amd64'

  # 步骤2: 构建 Docker 镜像
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/steez:$COMMIT_SHA', '.']

  # 步骤3: 推送镜像到 Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/steez:$COMMIT_SHA']

  # 步骤4: 部署到 Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'steez'
      - '--image'
      - 'gcr.io/$PROJECT_ID/steez:$COMMIT_SHA'
      - '--region'
      - 'asia-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8808'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'

# 镜像标签
images:
  - 'gcr.io/$PROJECT_ID/steez:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/steez:latest'

# 超时设置
timeout: '1200s'

# 选项
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8' 